  command = "npm run dev"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://api.luciferaliss.site/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200